/**
 * Shared places data for map and place cards
 * Used by both InteractiveMap and PlaceCardsGrid
 */

export interface Place {
  name: string
  category: string
  distance: string
  walkTime?: string
  image?: string
  rating?: number
  priceLevel?: string
  address: string
  description?: string
  mapQuery?: string
  lat?: number
  lng?: number
}

export const placesData: Place[] = [
  // DINING
  {
    name: 'SW Steakhouse',
    category: 'dining',
    distance: '0.3 mi',
    walkTime: '5 min walk',
    description: 'Fine dining',
    rating: 4.8,
    priceLevel: '$$$$',
    address: '3131 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'SW Steakhouse Wynn Las Vegas',
    lat: 36.1274,
    lng: -115.1642,
  },
  {
    name: 'Sinatra',
    category: 'dining',
    distance: '0.4 mi',
    walkTime: '6 min walk',
    description: 'Italian fine dining',
    rating: 4.7,
    priceLevel: '$$$$',
    address: '3131 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Sinatra Encore Las Vegas',
    lat: 36.1285,
    lng: -115.1651,
  },
  {
    name: 'Kassi Beach House',
    category: 'dining',
    distance: '0.2 mi',
    walkTime: '3 min walk',
    description: 'Mediterranean cuisine',
    rating: 4.6,
    priceLevel: '$$$',
    address: '3131 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Kassi Beach House Las Vegas',
    lat: 36.1263,
    lng: -115.1633,
  },
  {
    name: 'Bazaar Meat',
    category: 'dining',
    distance: '0.5 mi',
    walkTime: '8 min walk',
    description: 'José Andrés steakhouse',
    rating: 4.9,
    priceLevel: '$$$$',
    address: '3708 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Bazaar Meat José Andrés Las Vegas',
    lat: 36.1296,
    lng: -115.1662,
  },
  {
    name: 'Wing Lei',
    category: 'dining',
    distance: '0.3 mi',
    walkTime: '5 min walk',
    description: 'Chinese fine dining',
    rating: 4.8,
    priceLevel: '$$$$',
    address: '3131 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Wing Lei Wynn Las Vegas',
    lat: 36.1278,
    lng: -115.1645,
  },
  {
    name: 'Bartolotta Ristorante',
    category: 'dining',
    distance: '0.4 mi',
    walkTime: '6 min walk',
    description: 'Italian seafood',
    rating: 4.7,
    priceLevel: '$$$$',
    address: '3131 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Bartolotta Wynn Las Vegas',
    lat: 36.1289,
    lng: -115.1657,
  },

  // ENTERTAINMENT
  {
    name: 'Wynn Las Vegas',
    category: 'entertainment',
    distance: '0.3 mi',
    walkTime: '5 min walk',
    description: 'Resort/Casino',
    rating: 4.7,
    address: '3131 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Wynn Las Vegas',
    lat: 36.1274,
    lng: -115.1642,
  },
  {
    name: 'Encore',
    category: 'entertainment',
    distance: '0.4 mi',
    walkTime: '6 min walk',
    description: 'Resort/Casino',
    rating: 4.7,
    address: '3131 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Encore Las Vegas',
    lat: 36.1285,
    lng: -115.1651,
  },
  {
    name: 'Resorts World',
    category: 'entertainment',
    distance: '0.5 mi',
    walkTime: '8 min walk',
    description: 'Resort/Casino',
    rating: 4.6,
    address: '3000 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Resorts World Las Vegas',
    lat: 36.1296,
    lng: -115.1633,
  },
  {
    name: 'T-Mobile Arena',
    category: 'entertainment',
    distance: '1.2 mi',
    walkTime: '18 min walk',
    description: 'Sports/Concerts',
    rating: 4.8,
    address: '3780 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'T-Mobile Arena Las Vegas',
    lat: 36.1028,
    lng: -115.1784,
  },
  {
    name: 'Allegiant Stadium',
    category: 'entertainment',
    distance: '2.0 mi',
    description: 'NFL Stadium',
    rating: 4.9,
    address: '3333 Al Davis Way, Las Vegas, NV',
    mapQuery: 'Allegiant Stadium Las Vegas',
    lat: 36.0910,
    lng: -115.1844,
  },

  // SHOPPING
  {
    name: 'Fashion Show Mall',
    category: 'shopping',
    distance: '0.8 mi',
    walkTime: '12 min walk',
    description: '250+ stores',
    rating: 4.5,
    address: '3200 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Fashion Show Mall Las Vegas',
    lat: 36.1307,
    lng: -115.1696,
  },
  {
    name: 'Wynn Plaza',
    category: 'shopping',
    distance: '0.3 mi',
    walkTime: '5 min walk',
    description: 'Luxury retail',
    rating: 4.7,
    address: '3131 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Wynn Plaza Shops Las Vegas',
    lat: 36.1274,
    lng: -115.1642,
  },
  {
    name: 'Crystals',
    category: 'shopping',
    distance: '1.5 mi',
    description: 'High-end mall',
    rating: 4.6,
    address: '3720 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Crystals at CityCenter Las Vegas',
    lat: 36.1096,
    lng: -115.1754,
  },
  {
    name: 'The Forum Shops',
    category: 'shopping',
    distance: '1.8 mi',
    description: 'Luxury shopping',
    rating: 4.6,
    address: '3500 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Forum Shops Caesars Palace Las Vegas',
    lat: 36.1169,
    lng: -115.1737,
  },

  // COFFEE
  {
    name: 'Starbucks Reserve',
    category: 'coffee',
    distance: '0.3 mi',
    walkTime: '5 min walk',
    rating: 4.5,
    priceLevel: '$$',
    address: '3131 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Starbucks Reserve Wynn Las Vegas',
    lat: 36.1274,
    lng: -115.1642,
  },
  {
    name: 'Urth Caffé',
    category: 'coffee',
    distance: '0.4 mi',
    walkTime: '6 min walk',
    description: 'Organic coffee & tea',
    rating: 4.6,
    priceLevel: '$$',
    address: '3131 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Urth Caffé Wynn Las Vegas',
    lat: 36.1285,
    lng: -115.1651,
  },
  {
    name: 'Bouchon Bakery',
    category: 'coffee',
    distance: '0.3 mi',
    walkTime: '5 min walk',
    description: 'French bakery & café',
    rating: 4.7,
    priceLevel: '$$',
    address: '3131 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Bouchon Bakery Las Vegas',
    lat: 36.1278,
    lng: -115.1645,
  },

  // FITNESS
  {
    name: 'Wynn Fitness Center',
    category: 'fitness',
    distance: '0.3 mi',
    walkTime: '5 min walk',
    description: 'State-of-the-art gym',
    rating: 4.8,
    address: '3131 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Wynn Fitness Center Las Vegas',
    lat: 36.1274,
    lng: -115.1642,
  },
  {
    name: 'Equinox',
    category: 'fitness',
    distance: '0.8 mi',
    walkTime: '12 min walk',
    description: 'Premium fitness club',
    rating: 4.7,
    address: '3720 S Las Vegas Blvd, Las Vegas, NV',
    mapQuery: 'Equinox Las Vegas',
    lat: 36.1096,
    lng: -115.1754,
  },

  // SCHOOLS
  {
    name: 'Las Vegas Academy',
    category: 'schools',
    distance: '1.5 mi',
    description: 'Arts & Academic High School',
    rating: 4.5,
    address: '315 S 7th St, Las Vegas, NV',
    mapQuery: 'Las Vegas Academy',
    lat: 36.1656,
    lng: -115.1433,
  },
  {
    name: 'UNLV',
    category: 'schools',
    distance: '3.0 mi',
    description: 'University of Nevada, Las Vegas',
    rating: 4.4,
    address: '4505 S Maryland Pkwy, Las Vegas, NV',
    mapQuery: 'University of Nevada Las Vegas',
    lat: 36.1085,
    lng: -115.1436,
  },

  // PARKS
  {
    name: 'Paradise Park',
    category: 'parks',
    distance: '0.8 mi',
    walkTime: '12 min walk',
    description: 'Community park',
    rating: 4.3,
    address: '4775 S Maryland Pkwy, Las Vegas, NV',
    mapQuery: 'Paradise Park Las Vegas',
    lat: 36.1085,
    lng: -115.1436,
  },
  {
    name: 'Symphony Park',
    category: 'parks',
    distance: '2.0 mi',
    description: 'Urban park & cultural center',
    rating: 4.5,
    address: '300 S Grand Central Pkwy, Las Vegas, NV',
    mapQuery: 'Symphony Park Las Vegas',
    lat: 36.1656,
    lng: -115.1533,
  },
]
